name: 'Merge and cleanup'
description: 'Pushing to GitHub repository local changes'
author: 'ad-m'
branding:
  icon: upload-cloud
  color: green
inputs:
  github_token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
